
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#influxdb                                                                                                               
influxdb:
  api_version: 2
  ssl: false
  host: 141.145.199.142
  port: 8086
  token: !secret influx_token
  organization: !secret influx_organization
  bucket: hydroponics
  include:
    domains:
      - sensor

