esphome:
  name: roofwaterfarm-hydroponic

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  password: ""

mqtt:
  broker: 141.145.199.142
  #username: ""
  #password: !secret mqtt_password
  discovery: true

web_server:
  port: 80

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roofwaterfarm-Hydroponic"
    password: !secret ap_password

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: 18
    echo_pin: 19
    name: "Watertank Filling Level"

  - platform: dht
    pin: 13
    temperature:
      name: "Control Box Temperature"
    humidity:
      name: "Control Box Humidity"
    update_interval: 60s

  - platform: adc
    pin: GPIO34
    name: "Water Flow Level 1"
    update_interval: 5s
    unit_of_measurement: "V"
    #unit_of_measurement: "%"
    #filters:
    #- median:
    #    window_size: 7
    #    send_every: 4
    #    send_first_at: 1
    #- calibrate_linear:
    #    - 0.85 -> 0.00
    #    - 0.44 -> 100.00
    #- lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 2

switch:
  - platform: gpio
    name: "Pump"
    pin: 14